version: 1.0.{build}
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - ps: wget https://s3-eu-west-1.amazonaws.com/conanio/downloads/conan-win_0_3_0.exe -OutFile conan_installer.exe
  - cmd: conan_installer.exe /VERYSILENT
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\Conan\conan
  - cmd: conan --version
  
test_script:
  - cmd: conan test_package
